"""add_user_settings

Revision ID: aa3fd0d325c3
Revises: a1b2c3d4e5f6
Create Date: 2026-05-01 14:28:43.033823

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3fd0d325c3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('felhasznalo_nev', sa.String(length=64), nullable=False),
    sa.Column('felhasznalo_id', sa.Integer(), nullable=True),
    sa.Column('setting_class', sa.String(length=64), nullable=False),
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['felhasznalo_id'], ['felhasznalok.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_felhasznalo_nev'), ['felhasznalo_nev'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_setting_class'), ['setting_class'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_setting_class'))
        batch_op.drop_index(batch_op.f('ix_user_settings_felhasznalo_nev'))
        batch_op.drop_index(batch_op.f('ix_user_settings_felhasznalo_id'))

    op.drop_table('user_settings')
    # ### end Alembic commands ###
