"""add medal aware history

Revision ID: da3577360b3f
Revises: aa3fd0d325c3
Create Date: 2026-05-03 06:14:14.396184

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3577360b3f'
down_revision: Union[str, None] = 'aa3fd0d325c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('felhasznalo_erem_szerzesek',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('felhasznalo_nev', sa.String(length=64), nullable=False),
    sa.Column('felhasznalo_id', sa.Integer(), nullable=True),
    sa.Column('erem_id', sa.String(length=64), nullable=False),
    sa.Column('szerzett_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['felhasznalo_id'], ['felhasznalok.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('felhasznalo_erem_szerzesek', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_felhasznalo_erem_szerzesek_erem_id'), ['erem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_felhasznalo_erem_szerzesek_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_felhasznalo_erem_szerzesek_felhasznalo_nev'), ['felhasznalo_nev'], unique=False)
        batch_op.create_index(batch_op.f('ix_felhasznalo_erem_szerzesek_szerzett_at'), ['szerzett_at'], unique=False)

    # Non-repeatable medals stay in user history permanently.
    # Clear legacy expiry timestamps from already earned one-time medals.
    op.execute(
        """
        UPDATE felhasznalo_eremek
        SET lejarat_at = NULL
        WHERE lejarat_at IS NOT NULL
          AND erem_id IN (
              SELECT id FROM eremek WHERE COALESCE(ismetelheto, 0) = 0
          )
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('felhasznalo_erem_szerzesek', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_felhasznalo_erem_szerzesek_szerzett_at'))
        batch_op.drop_index(batch_op.f('ix_felhasznalo_erem_szerzesek_felhasznalo_nev'))
        batch_op.drop_index(batch_op.f('ix_felhasznalo_erem_szerzesek_felhasznalo_id'))
        batch_op.drop_index(batch_op.f('ix_felhasznalo_erem_szerzesek_erem_id'))

    op.drop_table('felhasznalo_erem_szerzesek')
    # ### end Alembic commands ###
